server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA-DEFAULT-ZONE}/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: multiserviciosfuentes-service
          uri: lb://multiserviciosfuentes-service
          predicates:
            - Path=/multiserviciosfuentes/**