server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/microservicesaws/microservicesgsinuiri
          default-label: master
          searchPaths: config-data
#          username: ${GIT_USER}
#          password: ${GIT_PASSWORD}
#          skip-ssl-validation: true
  security:
    user:
      name: root
      password: s3cr3t
