spring:
  config:
    import: configserver:http://localhost:8081
  application:
    name: multiserviciosfuentes-service
  cloud:
    config:
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8086

  datasource:
    url: jdbc:postgresql://localhost:5432/frank_db
    username: postgres
    password: giansm1992
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      .ddl-auto: update
  main:
    allow-circular-references: true

logging:
  .level:
    org:
      hibernate.SQL: DEBUG
      type: TRACE
  
springdoc:
  api-docs:
    path: /inventory-api-docs
  swagger-ui:
    path: /inventory-api-docs-ui.html

jwt:
  secret: thebackendsecuritysecretmustbeplacedhere
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000


